language: python

python:
  - 2.7

install:
    - git clone https://github.com/cloudify-cosmo/cloudify-cli --depth=1
    - cd cloudify-cli; pip install . -r requirements.txt; cd ..
    - pip install .
    - pip install flake8

script:
    - flake8 .
    - nosetests openstack_plugin_common:ExceptionRetryProxyTestCase --nologcapture --nocapture
